In [9]:
addpath([pwd '/machine-learning-ex6/ex6'])

easy_ham = glob('easy_ham/0*');
easy_ham_2 = glob('easy_ham_2/0*');
hard_ham = glob('hard_ham/0*');
spam_2 = glob('spam_2/0*');
spam = glob('spam/0*');

size(easy_ham)
size(easy_ham_2)
size(hard_ham)
size(spam)
size(spam_2)

file_globs = [easy_ham; easy_ham_2; hard_ham; spam_2; spam];

size(file_globs)

length(file_globs)

em = readFile(file_globs{3000});
pr = processEmailExtra(em);

for i = 1:length(file_globs)
    file_addr = file_globs{i};
    email = readFile(file_addr);
    processed = processEmailExtra(email);
    dlmwrite('examples',processed,'delimiter','','-append');
end

In [135]:
vocabList = getVocabListExtra();

In [136]:
length(vocabList)

ans =  1942


In [137]:
fclose('all')

ans = 0


In [138]:
examples_fid = fopen('examples');
X = [];
for email_index = 1:6046
    email = strsplit(fgetl(examples_fid));
    word_indices = [];
    for word_index = 1:length(email)
        word_indices = [word_indices; find(strcmp(vocabList,email{word_index}))];
    end
    features = emailFeaturesExtra(word_indices);
    X = [X ; features'];
end
fclose(examples_fid);

In [139]:
whos

Variables in the current scope:

   Attr Name              Size                     Bytes  Class
   ==== ====              ====                     =====  ===== 
        X              6046x1942                93930656  double
        a                 1x1                          8  double
        ans               1x1                          8  double
        easy_ham       2500x1                     117500  cell
        easy_ham_2     1400x1                      68600  cell
        em                1x6475                    6475  char
        email             1x212                     1048  cell
        email_index       1x1                          8  double
        examples_fid      1x1                          8  double
        features       1942x1                      15536  double
        file_addr         1x43                        43  char
        file_globs     6046x1                     282170  cell
        hard_ham        250x1                      11750  cell
       

In [140]:
y = [zeros(4150,1);ones(1896,1)];

In [141]:
length(y)

ans =  6046


In [142]:
whos

Variables in the current scope:

   Attr Name              Size                     Bytes  Class
   ==== ====              ====                     =====  ===== 
        X              6046x1942                93930656  double
        a                 1x1                          8  double
        ans               1x1                          8  double
        easy_ham       2500x1                     117500  cell
        easy_ham_2     1400x1                      68600  cell
        em                1x6475                    6475  char
        email             1x212                     1048  cell
        email_index       1x1                          8  double
        examples_fid      1x1                          8  double
        features       1942x1                      15536  double
        file_addr         1x43                        43  char
        file_globs     6046x1                     282170  cell
        hard_ham        250x1                      11750  cell
       

In [143]:
help randperm

'randperm' is a built-in function from the file libinterp/corefcn/rand.cc

 -- Built-in Function: randperm (N)
 -- Built-in Function: randperm (N, M)
     Return a row vector containing a random permutation of '1:N'.

     If M is supplied, return M unique entries, sampled without
     replacement from '1:N'.

     The complexity is O(N) in memory and O(M) in time, unless M < N/5,
     in which case O(M) memory is used as well.  The randomization is
     performed using rand().  All permutations are equally likely.

     See also: perms.

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org
mailing list.


In [147]:
shuffled_indices = randperm (6046);

In [148]:
length(unique(shuffled_indices))

ans =  6046


In [160]:
shuffled_X = X(shuffled_indices,:);
shuffled_y = y(shuffled_indices,:);

In [167]:
X = shuffled_X;
y = shuffled_y;

In [175]:
save SA_dat.mat X y

In [177]:
train_size = floor(0.6*length(y))

train_size =  3627


In [178]:
cv_size = floor(0.5 * (length(y)-train_size))

cv_size =  1209


In [179]:
test_size = length(y) - (train_size + cv_size)

test_size =  1210


In [180]:
train_size + cv_size + test_size

ans =  6046


In [182]:
X_train = X(1:train_size,:);
y_train = y(1:train_size,:);

In [183]:
size(X_train)
size(y_train)

ans =

   3627   1942

ans =

   3627      1



In [186]:
cv_start = train_size + 1
cv_end = cv_start + cv_size - 1
cv_end - cv_start + 1 ==  cv_size

cv_start =  3628
cv_end =  4836
ans =  1


In [187]:
X_cv = X(cv_start:cv_end,:);
y_cv = y(cv_start:cv_end,:);

In [188]:
size(X_cv)
size(y_cv)

ans =

   1209   1942

ans =

   1209      1



In [190]:
test_start = cv_end + 1
test_end = length(y)
test_end - test_start + 1 ==  test_size

test_start =  4837
test_end =  6046
ans =  1


In [191]:
X_test = X(test_start:test_end,:);
y_test = y(test_start:test_end,:);

In [192]:
size(X_test)
size(y_test)

ans =

   1210   1942

ans =

   1210      1



In [193]:
whos

Variables in the current scope:

   Attr Name                  Size                     Bytes  Class
   ==== ====                  ====                     =====  ===== 
        X                  6046x1942                93930656  double
        X_cv               1209x1942                18783024  double
        X_test             1210x1942                18798560  double
        X_train            3627x1942                56349072  double
        a                     1x1                          8  double
        ans                   1x2                         16  double
        cv_end                1x1                          8  double
        cv_size               1x1                          8  double
        cv_start              1x1                          8  double
        easy_ham           2500x1                     117500  cell
        easy_ham_2         1400x1                      68600  cell
        em                    1x6475                    6475  char
        

In [194]:
save SA_dat_train_cv_test.mat X_* y_*