In [1]:
A = [1 2;3 4; 5 6]

A =

   1   2
   3   4
   5   6



In [2]:
B = [11 12;13 14; 15 16]

B =

   11   12
   13   14
   15   16



In [3]:
C = [1 1;2 2]

C =

   1   1
   2   2



In [4]:
size(A)

ans =

   3   2



In [5]:
size(B)

ans =

   3   2



In [6]:
size(C)

ans =

   2   2



In [7]:
A * C

ans =

    5    5
   11   11
   17   17



In [8]:
A .* B

ans =

   11   24
   39   56
   75   96



In [9]:
A * B

error: operator *: nonconformant arguments (op1 is 3x2, op2 is 3x2)


In [10]:
A .^3

ans =

     1     8
    27    64
   125   216



In [11]:
A .^2

ans =

    1    4
    9   16
   25   36



In [12]:
1 ./A

ans =

   1.00000   0.50000
   0.33333   0.25000
   0.20000   0.16667



In [13]:
A

A =

   1   2
   3   4
   5   6



In [14]:
log(A(:,1))

ans =

   0.00000
   1.09861
   1.60944



In [15]:
exp(A(:,1))

ans =

     2.7183
    20.0855
   148.4132



In [16]:
neg_A = -1 * A

neg_A =

  -1  -2
  -3  -4
  -5  -6



In [17]:
abs(neg_A)

ans =

   1   2
   3   4
   5   6



In [18]:
-A

ans =

  -1  -2
  -3  -4
  -5  -6



In [19]:
v

error: 'v' undefined near line 1 column 1


In [20]:
v = 1;2;3

ans =  3


In [21]:
v

v =  1


In [22]:
v = (1:1:3)'

v =

   1
   2
   3



In [23]:
v + 1

ans =

   2
   3
   4



In [24]:
v + ones(length(v),1)

ans =

   2
   3
   4



In [25]:
(v + ones(length(v),1)) == (v+1)

ans =

   1
   1
   1



In [26]:
v'

ans =

   1   2   3



In [27]:
max(v)

ans =  3


In [28]:
[val,ind] = max(v)

val =  3
ind =  3


In [29]:
A

A =

   1   2
   3   4
   5   6



In [30]:
max(A)

ans =

   5   6



In [31]:
A >=3

ans =

   0   0
   1   1
   1   1



In [32]:
A > 3

ans =

   0   0
   0   1
   1   1



In [33]:
find(A<3)

ans =

   1
   4



In [34]:
A

A =

   1   2
   3   4
   5   6



In [35]:
v

v =

   1
   2
   3



In [36]:
find(v<3)

ans =

   1
   2



In [37]:
A

A =

   1   2
   3   4
   5   6



In [39]:
magic(2,2)

error: Invalid call to magic.  Correct usage is:

 -- Function File: magic (N)

Additional help for built-in functions and operators is
available in the online version of the manual.  Use the command
'doc <topic>' to search the manual index.

Help and information about Octave is also available on the WWW
at http://www.octave.org and via the help@octave.org
mailing list.


In [40]:
magic(2)

error: magic: N must be a positive integer not equal to 2
error: called from
    magic at line 37 column 5


In [41]:
magic(3)

ans =

   8   1   6
   3   5   7
   4   9   2



In [42]:
A = magic(4)

A =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1



In [43]:
A

A =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1



In [44]:
[r,c]=find(A>=11)

r =

   1
   2
   4
   4
   1
   3

c =

   1
   2
   2
   3
   4
   4



In [45]:
help find

'find' is a built-in function from the file libinterp/corefcn/find.cc

 -- Built-in Function: IDX = find (X)
 -- Built-in Function: IDX = find (X, N)
 -- Built-in Function: IDX = find (X, N, DIRECTION)
 -- Built-in Function: [i, j] = find (...)
 -- Built-in Function: [i, j, v] = find (...)
     Return a vector of indices of nonzero elements of a matrix, as a
     row if X is a row vector or as a column otherwise.

     To obtain a single index for each matrix element, Octave pretends
     that the columns of a matrix form one long vector (like Fortran
     arrays are stored).  For example:

          find (eye (2))
            => [ 1; 4 ]

     If two inputs are given, N indicates the maximum number of elements
     to find from the beginning of the matrix or vector.

     If three inputs are given, DIRECTION should be one of "first" or
     "last", requesting only the first or last N indices, respectively.
     However, the indices are always returned in ascending order.

     If two 

In [46]:
sum(A)

ans =

   34   34   34   34



In [47]:
whos

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        A           4x4                        128  double
        B           3x2                         48  double
        C           2x2                         32  double
        ans         1x4                         32  double
        c           6x1                         24  double
        ind         1x1                          8  double
        neg_A       3x2                         48  double
        r           6x1                         24  double
        v           3x1                         24  double
        val         1x1                          8  double

Total is 53 elements using 376 bytes



In [48]:
r

r =

   1
   2
   4
   4
   1
   3



In [49]:
sum(r)

ans =  15


In [50]:
prod(r)

ans =  96


In [51]:
floor(a)

error: 'a' undefined near line 1 column 7
error: evaluating argument list element number 1


In [52]:
floor(r)

ans =

   1
   2
   4
   4
   1
   3



In [53]:
r = rand(6)

r =

   0.937637   0.900143   0.619822   0.095604   0.512943   0.458426
   0.326835   0.577797   0.043528   0.887427   0.643955   0.316871
   0.802693   0.634773   0.961398   0.508949   0.761036   0.598955
   0.115502   0.618335   0.312890   0.312612   0.819965   0.048115
   0.611307   0.521778   0.583562   0.532033   0.308387   0.452815
   0.329171   0.708417   0.586371   0.227823   0.939059   0.550549



In [54]:
help rand

'rand' is a built-in function from the file libinterp/corefcn/rand.cc

 -- Built-in Function: rand (N)
 -- Built-in Function: rand (M, N, ...)
 -- Built-in Function: rand ([M N ...])
 -- Built-in Function: V = rand ("state")
 -- Built-in Function: rand ("state", V)
 -- Built-in Function: rand ("state", "reset")
 -- Built-in Function: V = rand ("seed")
 -- Built-in Function: rand ("seed", V)
 -- Built-in Function: rand ("seed", "reset")
 -- Built-in Function: rand (..., "single")
 -- Built-in Function: rand (..., "double")
     Return a matrix with random elements uniformly distributed on the
     interval (0, 1).

     The arguments are handled the same as the arguments for 'eye'.

     You can query the state of the random number generator using the
     form

          v = rand ("state")

     This returns a column vector V of length 625.  Later, you can
     restore the random number generator to the state V using the form

          rand ("state", v)

     You may also initialize t

In [55]:
r = rand(6,1)

r =

   0.176099
   0.303530
   0.378864
   0.081997
   0.821298
   0.644737



In [56]:
floor(r)

ans =

   0
   0
   0
   0
   0
   0



In [57]:
ceil(r)

ans =

   1
   1
   1
   1
   1
   1



In [58]:
max(rand(3),rand(3))

ans =

   0.82501   0.97323   0.57954
   0.60668   0.42797   0.62784
   0.73847   0.93388   0.20803



In [59]:
A

A =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1



In [60]:
max(A,[],1)

ans =

   16   14   15   13



In [61]:
max(A)

ans =

   16   14   15   13



In [62]:
max(A,[],2)

ans =

   16
   11
   12
   15



In [63]:
max(max(A))

ans =  16


In [65]:
max(A(:))

ans =  16


In [66]:
A

A =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1



In [67]:
sum(A,1)

ans =

   34   34   34   34



In [68]:
sum(1,A)

ans =  1


In [69]:
whos

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        A           4x4                        128  double
        B           3x2                         48  double
        C           2x2                         32  double
        ans         1x1                          8  double
        c           6x1                         24  double
        ind         1x1                          8  double
        neg_A       3x2                         48  double
        r           6x1                         48  double
        v           3x1                         24  double
        val         1x1                          8  double

Total is 50 elements using 376 bytes



In [70]:
B

B =

   11   12
   13   14
   15   16



In [71]:
sum(B,1)

ans =

   39   42



In [72]:
sum(B,2)

ans =

   23
   27
   31



In [73]:
help sum

'sum' is a built-in function from the file libinterp/corefcn/data.cc

 -- Built-in Function: sum (X)
 -- Built-in Function: sum (X, DIM)
 -- Built-in Function: sum (..., "native")
 -- Built-in Function: sum (..., "double")
 -- Built-in Function: sum (..., "extra")
     Sum of elements along dimension DIM.

     If DIM is omitted, it defaults to the first non-singleton
     dimension.

     The optional "type" input determines the class of the variable used
     for calculations.  If the argument "native" is given, then the
     operation is performed in the same type as the original argument,
     rather than the default double type.

     For example:

          sum ([true, true])
             => 2
          sum ([true, true], "native")
             => true

     On the contrary, if "double" is given, the sum is performed in
     double precision even for single precision inputs.

     For double precision inputs, the "extra" option will use a more
     accurate algorithm than straigh

In [74]:
sum(B,0)

error: sum: invalid dimension DIM = 0


In [75]:
B(:,1)

ans =

   11
   13
   15



In [76]:
B(1,:)

ans =

   11   12



In [77]:
A

A =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1



In [78]:
 sum(sum(A.*eye(4)))

ans =  34


In [79]:
eye(4)

ans =

Diagonal Matrix

   1   0   0   0
   0   1   0   0
   0   0   1   0
   0   0   0   1



In [80]:
flipud(eye(4))

ans =

Permutation Matrix

   0   0   0   1
   0   0   1   0
   0   1   0   0
   1   0   0   0



In [81]:
A_inv = pinv(A) %pseudo-inverse

A_inv =

   0.1011029  -0.0738971  -0.0613971   0.0636029
  -0.0363971   0.0386029   0.0261029   0.0011029
   0.0136029  -0.0113971  -0.0238971   0.0511029
  -0.0488971   0.0761029   0.0886029  -0.0863971



In [82]:
A_inv * A

ans =

   0.950000  -0.150000   0.150000   0.050000
  -0.150000   0.550000   0.450000   0.150000
   0.150000   0.450000   0.550000  -0.150000
   0.050000   0.150000  -0.150000   0.950000



In [83]:
A * A_inv

ans =

   0.950000  -0.150000   0.150000   0.050000
  -0.150000   0.550000   0.450000   0.150000
   0.150000   0.450000   0.550000  -0.150000
   0.050000   0.150000  -0.150000   0.950000



In [84]:
size(A)

ans =

   4   4



In [85]:
whos

Variables in the current scope:

   Attr Name        Size                     Bytes  Class
   ==== ====        ====                     =====  ===== 
        A           4x4                        128  double
        A_inv       4x4                        128  double
        B           3x2                         48  double
        C           2x2                         32  double
        ans         1x2                         16  double
        c           6x1                         24  double
        ind         1x1                          8  double
        neg_A       3x2                         48  double
        r           6x1                         48  double
        v           3x1                         24  double
        val         1x1                          8  double

Total is 67 elements using 512 bytes



In [86]:
A = magic(3)

A =

   8   1   6
   3   5   7
   4   9   2



In [87]:
A_inv = pinv(A)

A_inv =

   0.147222  -0.144444   0.063889
  -0.061111   0.022222   0.105556
  -0.019444   0.188889  -0.102778



In [88]:
A_inv * A

ans =

   1.00000   0.00000  -0.00000
  -0.00000   1.00000   0.00000
   0.00000   0.00000   1.00000



In [89]:
A * A_inv

ans =

   1.0000e+00  -1.2212e-14   6.3283e-15
   5.5511e-17   1.0000e+00  -2.2204e-16
  -5.9952e-15   1.2268e-14   1.0000e+00

