In [1]:
A

error: 'A' undefined near line 1 column 1


In [2]:
A = [1 2;
3 4;
5 6]

A =

   1   2
   3   4
   5   6



In [3]:
size(A)

ans =

   3   2



In [4]:
size(size(A))

ans =

   1   2



In [5]:
size(A,1)

ans =  3


In [6]:
size(A,2)

ans =  2


In [7]:
v = 1:1:4

v =

   1   2   3   4



In [8]:
lenght(v)

error: 'lenght' undefined near line 1 column 1


In [9]:
length(v)

ans =  4


In [10]:
A

A =

   1   2
   3   4
   5   6



In [11]:
length(A)

ans =  3


In [12]:
pwd

ans = /notebooks


In [13]:
cd ..

In [14]:
pwd

ans = /


In [15]:
cd ..

In [16]:
pwd

ans = /


In [17]:
ls

bin   dev  home  lib64	mnt	   opt	 root  sbin   srv  tmp	var
boot  etc  lib	 media	notebooks  proc  run   setup  sys  usr


In [18]:
cd notebooks

In [19]:
ls

Moving_Data_Around.ipynb  OctaveBasics.ipynb  basics.ipynb  xyz.txt  xyzabc.txt


In [20]:
who

Variables in the current scope:

A    ans  v



In [21]:
pwd

ans = /notebooks


In [22]:
load('featuresX.dat')

In [23]:
load('priceY.dat')

In [24]:
who

Variables in the current scope:

A          ans        featuresX  priceY     v



In [25]:
whos

Variables in the current scope:

   Attr Name           Size                     Bytes  Class
   ==== ====           ====                     =====  ===== 
        A              3x2                         48  double
        ans            1x10                        10  char
        featuresX      6x2                         96  double
        priceY         6x1                         48  double
        v              1x4                         24  double

Total is 38 elements using 226 bytes



In [26]:
ans

ans = /notebooks


In [27]:
clear ans

In [28]:
whos

Variables in the current scope:

   Attr Name           Size                     Bytes  Class
   ==== ====           ====                     =====  ===== 
        A              3x2                         48  double
        featuresX      6x2                         96  double
        priceY         6x1                         48  double
        v              1x4                         24  double

Total is 28 elements using 216 bytes



In [29]:
v = priceY(1:3)

v =

   100
   120
   140



In [30]:
save hello.mat v

In [31]:
ls

Moving_Data_Around.ipynb  basics.ipynb	 hello.mat   xyz.txt
OctaveBasics.ipynb	  featuresX.dat  priceY.dat  xyzabc.txt


In [32]:
cat hello.mat

error: invalid conversion from string to real scalar
error: octave_base_value::int_value (): wrong type argument 'sq_string'
error: cat: DIM must be an integer


In [33]:
save hello.txt v -ascii

In [34]:
whos

Variables in the current scope:

   Attr Name           Size                     Bytes  Class
   ==== ====           ====                     =====  ===== 
        A              3x2                         48  double
        featuresX      6x2                         96  double
        priceY         6x1                         48  double
        v              3x1                         24  double

Total is 27 elements using 216 bytes



In [35]:
A

A =

   1   2
   3   4
   5   6



In [36]:
A(3,1)

ans =  5


In [37]:
A(2,:)

ans =

   3   4



In [38]:
A(:,2)

ans =

   2
   4
   6



In [39]:
A([1 3],:)

ans =

   1   2
   5   6



In [40]:
A(:,2) = [10 11 12]

A =

    1   10
    3   11
    5   12



In [41]:
A

A =

    1   10
    3   11
    5   12



In [42]:
A(:,2) = [10 11 12 13]

error: A(I,J,...) = X: dimensions mismatch


In [43]:
A[2,:] = [100 99]

parse error:

  syntax error

>>> A[2,:] = [100 99]
     ^



In [44]:
A(2,:) = [100 99]

A =

     1    10
   100    99
     5    12



In [45]:
A = [A,[101,102,103]]

error: horizontal dimensions mismatch (3x2 vs 1x3)


In [46]:
A = [A,[101;102;103]]

A =

     1    10   101
   100    99   102
     5    12   103



In [48]:
A = [A;[105,106,107]]

A =

     1    10   101
   100    99   102
     5    12   103
   105   106   107



In [51]:
size(A)

ans =

   4   3



In [49]:
A(:)

ans =

     1
   100
     5
   105
    10
    99
    12
   106
   101
   102
   103
   107



In [52]:
size(A(:))

ans =

   12    1



In [53]:
X = [1 2 ; 3 4]

X =

   1   2
   3   4



In [54]:
Y = [10 9; 8 7]

Y =

   10    9
    8    7



In [ ]:
Z = {}